# Generated by Katalon Recorder
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re


class Test016(unittest.TestCase):
    def setUp(self):
        # AppDynamics will automatically override this web driver
        # as documented in https://docs.appdynamics.com/display/PRO44/Write+Your+First+Script
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(5)
        self.base_url = "https://www.google.com/"
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_016(self):
        driver = self.driver
        driver.get("https://www.spotify.com/ar/signup/?forward_url=https%3A%2F%2Fwww.spotify.com%2Far%2Fdownload%2F")
        driver.find_element_by_id("email").click()
        driver.find_element_by_id("email").clear()
        driver.find_element_by_id("email").send_keys("mattg1593@gmail.com")
        driver.find_element_by_xpath("//div[@id='__next']/main/div[2]/form/div[2]").click()
        driver.find_element_by_id("confirm").clear()
        driver.find_element_by_id("confirm").send_keys("mattg1593@gmail.com")
        driver.find_element_by_id("password").click()
        driver.find_element_by_id("password").clear()
        driver.find_element_by_id("password").send_keys("123456789")
        driver.find_element_by_id("displayname").click()
        driver.find_element_by_id("displayname").clear()
        driver.find_element_by_id("displayname").send_keys("Matias")
        driver.find_element_by_id("day").click()
        driver.find_element_by_id("day").clear()
        driver.find_element_by_id("day").send_keys("15")
        Select(driver.find_element_by_id("month")).select_by_visible_text("Septiembre")
        driver.find_element_by_id("year").clear()
        driver.find_element_by_id("year").send_keys("1993")
        driver.find_element_by_xpath("//div[@id='__next']/main/div[2]/form/div[6]/div[2]/label/span").click()
        driver.find_element_by_xpath("//button[@type='submit']").click()

    def is_element_present(self, how, what):
        try:
            self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e:
            return False
        return True

    def is_alert_present(self):
        try:
            self.driver.switch_to_alert()
        except NoAlertPresentException as e:
            return False
        return True

    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally:
            self.accept_next_alert = True

    def tearDown(self):
        # To know more about the difference between verify and assert,
        # visit https://www.seleniumhq.org/docs/06_test_design_considerations.jsp#validating-results
        self.assertEqual([], self.verificationErrors)
        self.driver.close()


if __name__ == "__main__":
    unittest.main()
