# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test017:

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_017(self):
        self.driver.get("https://www.spotify.com/ar/signup/?forward_url=https%3A%2F%2Fwww.spotify.com%2Far%2Fdownload%2F")
        self.driver.set_window_size(1920, 1015)
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("mattg1593@gmail.com")
        element = self.driver.find_element(By.ID, "confirm")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".Group-sc-1lird8m-0:nth-child(2) .Label-jt4b9o-0")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.CSS_SELECTOR, ".Group-sc-1lird8m-0:nth-child(2)").click()
        self.driver.find_element(By.ID, "confirm").send_keys("mattg1593@gmail.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("123456798")
        self.driver.find_element(By.ID, "displayname").click()
        self.driver.find_element(By.ID, "displayname").send_keys("Matias")
        self.driver.find_element(By.ID, "day").click()
        self.driver.find_element(By.ID, "day").send_keys("15")
        self.driver.find_element(By.ID, "month").click()
        dropdown = self.driver.find_element(By.ID, "month")
        dropdown.find_element(By.XPATH, "//option[. = 'Septiembre']").click()
        self.driver.find_element(By.ID, "month").click()
        self.driver.find_element(By.ID, "year").click()
        self.driver.find_element(By.ID, "year").send_keys("1993")
        self.driver.find_element(By.CSS_SELECTOR, ".Radio-fatlcr-0:nth-child(1) > .Type__TypeElement-sc-9snywk-0").click()
        self.driver.switch_to.frame(1)
        self.driver.switch_to.default_content()
        self.driver.find_element(By.CSS_SELECTOR, ".fivrVz").click()

